#include "formats.h"

enum {
	ROCKETCHATTXT_MODULE_NAME,

	ROCKETCHATTXT_FILL_1,

	ROCKETCHATTXT_OWN_MSG,
	ROCKETCHATTXT_OWN_MSG_THREAD,
	ROCKETCHATTXT_OWN_MSG_CHANNEL,
	ROCKETCHATTXT_OWN_MSG_CHANNEL_THREAD,
	ROCKETCHATTXT_OWN_MSG_PRIVATE,
	ROCKETCHATTXT_OWN_MSG_PRIVATE_THREAD,
	ROCKETCHATTXT_OWN_MSG_PRIVATE_QUERY,
	ROCKETCHATTXT_OWN_MSG_PRIVATE_QUERY_THREAD,
	ROCKETCHATTXT_PUBMSG_ME,
	ROCKETCHATTXT_PUBMSG_ME_THREAD,
	ROCKETCHATTXT_PUBMSG_ME_CHANNEL,
	ROCKETCHATTXT_PUBMSG_ME_CHANNEL_THREAD,
	ROCKETCHATTXT_PUBMSG_HILIGHT,
	ROCKETCHATTXT_PUBMSG_HILIGHT_THREAD,
	ROCKETCHATTXT_PUBMSG_HILIGHT_CHANNEL,
	ROCKETCHATTXT_PUBMSG_HILIGHT_CHANNEL_THREAD,
	ROCKETCHATTXT_PUBMSG,
	ROCKETCHATTXT_PUBMSG_THREAD,
	ROCKETCHATTXT_PUBMSG_CHANNEL,
	ROCKETCHATTXT_PUBMSG_CHANNEL_THREAD,
	ROCKETCHATTXT_MSG_PRIVATE,
	ROCKETCHATTXT_MSG_PRIVATE_THREAD,
	ROCKETCHATTXT_MSG_PRIVATE_QUERY,
	ROCKETCHATTXT_MSG_PRIVATE_QUERY_THREAD,
};

extern FORMAT_REC fecommon_rocketchat_formats[];
